INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Saul','Medina','saul@correo.com','2020-05-15','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Luis Angel','Mondragon','luis@correo.com','2005-07-11','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Ernesto','Hernandez','ernesto@correo.com','2020-10-15','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Carmen','Espinoza','carmen@correo.com','200-02-01','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Jose','Mendoza','jose@correo.com','2001-08-16','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Julio','Rios','julio@correo.com','2000-03-05','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Uriel','Garcia','uriel@correo.com','1997-05-19','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Jaime','Osorio','Jaime@correo.com','2015-12-11','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Hugo','Cervantes','hugo@correo.com','2000-08-14','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Fernando','Salazar','fernando@correo.com','2015-02-12','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Alfredo','Montes de OCa','alfredo@correo.com','2001-02-10','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Cesar','Orlando','cesar@correo.com','2002-01-10','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Mario','Jimenez','mario@correo.com','2000-01-12','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Gerardo','Pilares','gerardo@correo.com','2000-01-13','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Benito','Rodriguez','benito@correo.com','1995-07-19','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Alma','Gonzales','alma@correo.com','1992-04-12','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Nicol','Lucia','nicol@correo.com','2002-01-10','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Zoe','Benitez','zoe@correo.com','1998-08-19','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Ximena','Medina','ximena@correo.com','1999-09-19','');
INSERT INTO clientes (name,lastname,email,create_at,foto) VALUES('Dario','Vilchis','dario@correo.com','1995-01-18','');